/**
 * Emerson Park Design & Construction
 * Three-Stage Visual Style Quiz — Question Bank
 *
 * STAGE 1 — Exterior Discovery  (11 questions)
 * STAGE 2 — Interior Discovery  (10 questions)
 * STAGE 3 — Project Details     (form, not questions — defined in QuizFlow)
 *
 * Signal codes
 * ─────────────────────────────────────────────────────────────────────────────
 * Architectural (exterior):
 *   WM  Warm Modern        MF  Modern Farmhouse     TR  New Traditional
 *   CC  Coastal Contemporary  MS  Contemporary Mediterranean  OM  Organic Modern
 *   MC  Modern Cottage     MB  Modern Barn          MM  Mountain Modern
 *   MP  Modern Prairie
 *
 * Interior Finish:
 *   MCL  Modern Clean      WN  Warm Natural         CE  Classic Elevated
 *   CL   Coastal Light     MT  Mediterranean Textured  OS  Organic Spa
 *   CTG  Cottage Character  RI  Rustic / Industrial
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface QuizOption {
  id: string;
  label: string;
  description: string;
  gradient: string;
  emoji: string;
  signals: string[];
}

export interface StageQuestion {
  id: string;
  prompt: string;
  type: "single" | "multi" | "multi-limited";
  maxSelections?: number;
  options: QuizOption[];
}

// ─── Style code name maps ─────────────────────────────────────────────────────

export const ARCH_STYLES: Record<string, string> = {
  WM: "Warm Modern",
  MF: "Modern Farmhouse",
  TR: "New Traditional",
  CC: "Coastal Contemporary",
  MS: "Contemporary Mediterranean",
  OM: "Organic Modern",
  MC: "Modern Cottage",
  MB: "Modern Barn",
  MM: "Mountain Modern",
  MP: "Modern Prairie",
};

export const FINISH_STYLES: Record<string, string> = {
  MCL: "Modern Clean",
  WN: "Warm Natural",
  CE: "Classic Elevated",
  CL: "Coastal Light",
  MT: "Mediterranean Textured",
  OS: "Organic Spa",
  CTG: "Cottage Character",
  RI: "Rustic / Industrial",
};

// ─── STAGE 1 — Exterior Discovery (11 questions) ──────────────────────────────

export const STAGE_1_QUESTIONS: StageQuestion[] = [
  {
    id: "ext_1",
    prompt: "Which exterior homes are you most drawn to for your new home?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Warm Modern Retreat",
        description: "Clean massing, large glass, warm wood accents — modern but livable",
        signals: ["WM", "OM"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "🏡",
      },
      {
        id: "B",
        label: "Modern Farmhouse 2.0",
        description: "Gabled roofs, white & black palette, approachable luxury",
        signals: ["MF", "TR"],
        gradient: "from-slate-700 to-slate-400",
        emoji: "🌾",
      },
      {
        id: "C",
        label: "New Traditional Estate",
        description: "Symmetry, timelessness, classic curb appeal, resale confidence",
        signals: ["TR", "CE"],
        gradient: "from-zinc-700 to-zinc-500",
        emoji: "🏛️",
      },
      {
        id: "D",
        label: "Coastal Contemporary",
        description: "Light palette, pool lifestyle, natural light, casual luxury",
        signals: ["CC", "CL"],
        gradient: "from-sky-600 to-cyan-300",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Modern Mediterranean",
        description: "Arches, texture, courtyard, romantic exterior, regional character",
        signals: ["MS", "MT"],
        gradient: "from-orange-700 to-amber-500",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "European Cottage Modern",
        description: "Character, warmth, charm, intimate luxury, layered detail",
        signals: ["MC", "TR", "CTG"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "🌸",
      },
      {
        id: "G",
        label: "Modern Barn Residence",
        description: "Dramatic volume, utility, flexible living, strong masculine edge",
        signals: ["MB", "MM"],
        gradient: "from-stone-800 to-neutral-600",
        emoji: "🏗️",
      },
      {
        id: "H",
        label: "Modern Prairie",
        description: "Horizontal massing, privacy, indoor-outdoor connection, refined calm",
        signals: ["MP", "WM", "OM"],
        gradient: "from-amber-900 to-stone-600",
        emoji: "🌅",
      },
    ],
  },

  {
    id: "ext_2",
    prompt: "Which overall home shape feels closest to what you would want?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Simple Rectangular Modern",
        description: "Clean, efficient, modern form",
        signals: ["WM", "MP", "MCL"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "◻️",
      },
      {
        id: "B",
        label: "Classic Symmetrical Front",
        description: "Formal, timeless, resale-friendly",
        signals: ["TR", "CE"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "⚖️",
      },
      {
        id: "C",
        label: "Gabled Family Home",
        description: "Approachable, casual, traditional-modern blend",
        signals: ["MF", "MC"],
        gradient: "from-slate-600 to-slate-400",
        emoji: "🏠",
      },
      {
        id: "D",
        label: "Courtyard-Oriented Home",
        description: "Indoor-outdoor living, privacy, resort feel",
        signals: ["MS", "CC", "OM"],
        gradient: "from-amber-700 to-orange-400",
        emoji: "🏡",
      },
      {
        id: "E",
        label: "L-Shape or U-Shape Plan",
        description: "Functional zoning, outdoor planning, privacy",
        signals: ["WM", "CC", "MP"],
        gradient: "from-teal-700 to-teal-400",
        emoji: "📐",
      },
      {
        id: "F",
        label: "Tall Volume Statement",
        description: "Drama, scale, custom design, bold presence",
        signals: ["MB", "MM", "WM"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🗼",
      },
      {
        id: "G",
        label: "Long Low Horizontal",
        description: "Calm, private, land-hugging architecture",
        signals: ["MP", "OM", "WM"],
        gradient: "from-amber-800 to-stone-500",
        emoji: "➡️",
      },
      {
        id: "H",
        label: "Layered Cottage Massing",
        description: "Character, detail, intimate scale",
        signals: ["MC", "TR", "CTG"],
        gradient: "from-rose-700 to-stone-400",
        emoji: "🌺",
      },
    ],
  },

  {
    id: "ext_3",
    prompt: "Which rooflines would you want considered for your new home?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Low-Slope Modern Roof",
        description: "Sleek, horizontal, contemporary",
        signals: ["WM", "MP"],
        gradient: "from-zinc-700 to-zinc-500",
        emoji: "▱",
      },
      {
        id: "B",
        label: "Simple Gable Roof",
        description: "Familiar, warm, clean",
        signals: ["MF", "MC", "MB"],
        gradient: "from-slate-600 to-slate-400",
        emoji: "⛺",
      },
      {
        id: "C",
        label: "Multiple Gables",
        description: "Detailed, classic, family home feel",
        signals: ["TR", "MC", "MF"],
        gradient: "from-stone-600 to-stone-300",
        emoji: "🏘️",
      },
      {
        id: "D",
        label: "Hip Roof Traditional",
        description: "Timeless, formal, resale-friendly",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "🏠",
      },
      {
        id: "E",
        label: "Flat Tile / Low Mediterranean",
        description: "Regional, warm, textured character",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🫙",
      },
      {
        id: "F",
        label: "Steep Cottage Roof",
        description: "Charm, character, intimate detail",
        signals: ["MC", "CTG"],
        gradient: "from-rose-600 to-stone-400",
        emoji: "🏡",
      },
      {
        id: "G",
        label: "Dramatic Barn Roof",
        description: "Volume, utility, statement architecture",
        signals: ["MB", "MM", "RI"],
        gradient: "from-stone-800 to-stone-600",
        emoji: "🏚️",
      },
      {
        id: "H",
        label: "Mixed Modern Roofline",
        description: "Custom, layered, contemporary blend",
        signals: ["WM", "OM", "MP"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "✦",
      },
    ],
  },

  {
    id: "ext_4",
    prompt: "Which exterior material combinations are you most drawn to?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Stucco + Wood + Stone",
        description: "Warm natural, refined modern blend",
        signals: ["WM", "OM", "MS"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "🪵",
      },
      {
        id: "B",
        label: "White Siding + Black Windows + Metal",
        description: "Clean contrast, modern farmhouse feel",
        signals: ["MF", "TR"],
        gradient: "from-slate-800 to-slate-400",
        emoji: "🖤",
      },
      {
        id: "C",
        label: "Brick + Painted Trim",
        description: "Timeless, formal, excellent resale",
        signals: ["TR", "CE"],
        gradient: "from-red-800 to-rose-600",
        emoji: "🧱",
      },
      {
        id: "D",
        label: "Smooth Stucco + Arches + Iron",
        description: "Romantic, textured, regional character",
        signals: ["MS", "MT"],
        gradient: "from-orange-700 to-amber-500",
        emoji: "🌿",
      },
      {
        id: "E",
        label: "Light Stucco + Pale Stone + Glass",
        description: "Light, airy, pool-oriented luxury",
        signals: ["CC", "CL"],
        gradient: "from-sky-500 to-cyan-200",
        emoji: "💎",
      },
      {
        id: "F",
        label: "Stone + Timber + Dark Windows",
        description: "Dramatic, grounded, masculine presence",
        signals: ["MM", "MB", "RI"],
        gradient: "from-stone-800 to-stone-600",
        emoji: "🪨",
      },
      {
        id: "G",
        label: "Mixed Stone + Soft Brick + Trim",
        description: "Character, layered detail, warmth",
        signals: ["MC", "CTG", "TR"],
        gradient: "from-stone-600 to-rose-400",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Dark Metal + Wood + Glass",
        description: "Bold, custom, dramatic statement",
        signals: ["MB", "WM", "RI"],
        gradient: "from-zinc-800 to-stone-600",
        emoji: "⚡",
      },
    ],
  },

  {
    id: "ext_5",
    prompt: "Which exterior color palettes feel right for your new home?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Warm White + Natural Wood + Soft Stone",
        description: "Soft, clean, warm luxury",
        signals: ["WM", "OM", "CC"],
        gradient: "from-amber-200 to-stone-300",
        emoji: "🤍",
      },
      {
        id: "B",
        label: "Crisp White + Black Accents",
        description: "Contrast, simple, modern familiar",
        signals: ["MF", "TR"],
        gradient: "from-slate-900 to-slate-300",
        emoji: "◐",
      },
      {
        id: "C",
        label: "Soft Greige + Taupe + Bronze",
        description: "Understated luxury, refined warmth",
        signals: ["WM", "MS", "OM"],
        gradient: "from-amber-700 to-stone-300",
        emoji: "🏺",
      },
      {
        id: "D",
        label: "Charcoal + Wood + Stone",
        description: "Dramatic, bold, strong presence",
        signals: ["MB", "MM", "RI"],
        gradient: "from-zinc-800 to-stone-500",
        emoji: "🖤",
      },
      {
        id: "E",
        label: "Pale Coastal Whites + Sand Tones",
        description: "Relaxed, airy, outdoor-focused",
        signals: ["CC", "CL"],
        gradient: "from-sky-200 to-amber-100",
        emoji: "🏖️",
      },
      {
        id: "F",
        label: "Earthy Mediterranean Tones",
        description: "Warm, regional, handcrafted texture",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌺",
      },
      {
        id: "G",
        label: "Classic Brick or Painted Brick",
        description: "Classic, refined, enduring appeal",
        signals: ["TR", "CE", "MC"],
        gradient: "from-red-700 to-rose-500",
        emoji: "🧱",
      },
      {
        id: "H",
        label: "Organic Monochrome Neutrals",
        description: "Calm, natural, elevated simplicity",
        signals: ["OM", "OS", "WN"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🌿",
      },
    ],
  },

  {
    id: "ext_6",
    prompt: "What kind of front entry experience would you want for your new home?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Tall Modern Glass Entry",
        description: "Custom, dramatic, modern welcome",
        signals: ["WM", "OM"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "🚪",
      },
      {
        id: "B",
        label: "Covered Farmhouse Porch",
        description: "Casual, family, approachable warmth",
        signals: ["MF"],
        gradient: "from-slate-600 to-slate-300",
        emoji: "🌾",
      },
      {
        id: "C",
        label: "Formal Symmetrical Entry",
        description: "Timeless, formal, impressive arrival",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "⚖️",
      },
      {
        id: "D",
        label: "Arched Mediterranean Entry",
        description: "Romantic, textured, distinctive character",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "E",
        label: "Coastal Breezeway Entry",
        description: "Relaxed, airy, outdoor connection",
        signals: ["CC", "CL"],
        gradient: "from-sky-500 to-cyan-300",
        emoji: "🌊",
      },
      {
        id: "F",
        label: "Cottage Garden Entry",
        description: "Warmth, character, charming approach",
        signals: ["MC", "CTG"],
        gradient: "from-rose-500 to-stone-400",
        emoji: "🌸",
      },
      {
        id: "G",
        label: "Barn-Style Oversized Entry",
        description: "Statement, dramatic scale, bold",
        signals: ["MB", "MM"],
        gradient: "from-stone-700 to-stone-500",
        emoji: "🏚️",
      },
      {
        id: "H",
        label: "Private Courtyard Entry",
        description: "Resort-like, private, high-end experience",
        signals: ["MS", "OM", "CC"],
        gradient: "from-teal-700 to-amber-500",
        emoji: "🏡",
      },
    ],
  },

  {
    id: "ext_7",
    prompt: "Which window and natural light styles are you most drawn to?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Large Modern Black Windows",
        description: "Modern, bright, strong visual frame",
        signals: ["WM", "MP", "MCL"],
        gradient: "from-zinc-800 to-zinc-500",
        emoji: "⬛",
      },
      {
        id: "B",
        label: "Gridded Farmhouse Windows",
        description: "Familiar, warm, traditional feel",
        signals: ["MF", "MC", "CTG"],
        gradient: "from-slate-600 to-slate-300",
        emoji: "🔲",
      },
      {
        id: "C",
        label: "Classic Divided-Light Windows",
        description: "Timeless, formal, refined detail",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "🪟",
      },
      {
        id: "D",
        label: "Arched Windows",
        description: "Romantic, architectural detail, statement",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "E",
        label: "Floor-to-Ceiling Glass Walls",
        description: "Indoor-outdoor, luxury, expansive light",
        signals: ["WM", "CC", "OM"],
        gradient: "from-sky-600 to-cyan-300",
        emoji: "✨",
      },
      {
        id: "F",
        label: "Clerestory Windows",
        description: "Modern, private, design sophistication",
        signals: ["MP", "OM"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "💡",
      },
      {
        id: "G",
        label: "Cottage-Style Windows",
        description: "Character, charm, intimate scale",
        signals: ["MC", "CTG"],
        gradient: "from-rose-500 to-stone-400",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Sliding / Folding Glass Doors",
        description: "Outdoor priority, entertaining, open living",
        signals: ["CC", "WM", "OM"],
        gradient: "from-teal-600 to-cyan-300",
        emoji: "🏡",
      },
    ],
  },

  {
    id: "ext_8",
    prompt: "Which garage and arrival layout would you want considered?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Side-Entry Garage",
        description: "Upscale curb appeal, garage de-emphasized",
        signals: ["TR", "WM"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "🚗",
      },
      {
        id: "B",
        label: "Front-Load with Upgraded Doors",
        description: "Practical, design integrated",
        signals: ["MF", "TR"],
        gradient: "from-slate-600 to-slate-400",
        emoji: "🏠",
      },
      {
        id: "C",
        label: "Detached / Carriage House",
        description: "Estate feel, flexibility, character",
        signals: ["MC", "MF", "MB"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "🏡",
      },
      {
        id: "D",
        label: "Motor Court Arrival",
        description: "Luxury, formal, custom impression",
        signals: ["TR", "MS", "WM"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "✦",
      },
      {
        id: "E",
        label: "Oversized Workshop Garage",
        description: "Utility, lifestyle function, hobbyist",
        signals: ["MB", "MM", "RI"],
        gradient: "from-stone-800 to-stone-600",
        emoji: "🔧",
      },
      {
        id: "F",
        label: "Hidden / Recessed Garage",
        description: "Design-forward, strong curb appeal",
        signals: ["WM", "MP", "OM"],
        gradient: "from-zinc-700 to-zinc-500",
        emoji: "👁️",
      },
      {
        id: "G",
        label: "RV / Boat / Toy Storage",
        description: "Function-heavy, land-oriented",
        signals: ["MB", "MM"],
        gradient: "from-stone-700 to-stone-500",
        emoji: "🚤",
      },
      {
        id: "H",
        label: "Porte-Cochère / Covered Arrival",
        description: "Luxury, formal hospitality",
        signals: ["TR", "MS", "CE"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🏛️",
      },
    ],
  },

  {
    id: "ext_9",
    prompt: "Which outdoor living areas would you want planned from the beginning?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Modern Covered Lanai + Pool View",
        description: "Indoor-outdoor, entertaining, resort feel",
        signals: ["WM", "CC", "OM"],
        gradient: "from-teal-600 to-cyan-300",
        emoji: "🏊",
      },
      {
        id: "B",
        label: "Farmhouse Porch + Outdoor Fireplace",
        description: "Casual comfort, gathering, cozy outdoor",
        signals: ["MF", "MC"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "🔥",
      },
      {
        id: "C",
        label: "Formal Pool Terrace",
        description: "Classic luxury, formal entertaining",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Mediterranean Courtyard Pool",
        description: "Private, resort, romantic character",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "E",
        label: "Coastal Resort Pool",
        description: "Resort lifestyle, bright, social",
        signals: ["CC", "CL"],
        gradient: "from-sky-500 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "F",
        label: "Organic Spa Courtyard",
        description: "Privacy, wellness, calm retreat",
        signals: ["OM", "OS"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Rustic Modern Outdoor Living",
        description: "Drama, entertaining, grounded feel",
        signals: ["MM", "RI"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🏕️",
      },
      {
        id: "H",
        label: "Large Land-Based Outdoor Zone",
        description: "Acreage, function, active lifestyle",
        signals: ["MB", "MM"],
        gradient: "from-amber-800 to-stone-600",
        emoji: "🌄",
      },
    ],
  },

  {
    id: "ext_10",
    prompt: "When you imagine walking into your new home, which main living space feels most like what you want?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Warm Modern Open Living",
        description: "Clean but warm, elevated comfort",
        signals: ["WM", "WN", "OM"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🏡",
      },
      {
        id: "B",
        label: "Bright Farmhouse Great Room",
        description: "Casual, family-oriented, open",
        signals: ["MF", "CTG"],
        gradient: "from-slate-600 to-slate-300",
        emoji: "🌾",
      },
      {
        id: "C",
        label: "Elegant Transitional Living",
        description: "Polished, timeless, refined",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Coastal Light Open Space",
        description: "Relaxed, bright, casual luxury",
        signals: ["CC", "CL"],
        gradient: "from-sky-500 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Textured Living",
        description: "Romantic, textured, warm character",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Organic Spa-Inspired Living",
        description: "Calm, wellness, soft modern luxury",
        signals: ["OM", "OS"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Cottage Character Living",
        description: "Cozy, detailed, intimate",
        signals: ["MC", "CTG"],
        gradient: "from-rose-500 to-stone-400",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Rustic Modern Volume Space",
        description: "Dramatic, high-volume, statement",
        signals: ["MM", "MB", "RI"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🏗️",
      },
    ],
  },

  {
    id: "ext_11",
    prompt:
      "If you had to choose one direction that feels most exciting for your new home — which would you want our design team to study most closely?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Clean Warm Modern",
        description: "WM + OM — the highest-confidence modern direction",
        signals: ["WM", "OM"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🏡",
      },
      {
        id: "B",
        label: "Refined Modern Farmhouse",
        description: "MF + TR — family-friendly approachable luxury",
        signals: ["MF", "TR"],
        gradient: "from-slate-700 to-slate-400",
        emoji: "🌾",
      },
      {
        id: "C",
        label: "Transitional Estate",
        description: "TR + CE — resale-friendly timeless design",
        signals: ["TR", "CE"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "🏛️",
      },
      {
        id: "D",
        label: "Coastal Contemporary",
        description: "CC + CL — outdoor lifestyle and resort feel",
        signals: ["CC", "CL"],
        gradient: "from-sky-600 to-cyan-300",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Contemporary Mediterranean",
        description: "MS + MT — romantic, distinctive, regional",
        signals: ["MS", "MT"],
        gradient: "from-orange-700 to-amber-500",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Organic Modern",
        description: "OM + OS — quiet luxury, wellness-inspired",
        signals: ["OM", "OS"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Modern Cottage / European",
        description: "MC + CTG — personality, warmth, character",
        signals: ["MC", "CTG"],
        gradient: "from-rose-600 to-stone-400",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Modern Barn / Rustic Modern",
        description: "MB + MM — scale, function, dramatic volume",
        signals: ["MB", "MM", "RI"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🏚️",
      },
    ],
  },
];

// ─── STAGE 2 — Interior Discovery (10 questions) ──────────────────────────────

export const STAGE_2_QUESTIONS: StageQuestion[] = [
  {
    id: "int_1",
    prompt:
      "Which interior finish directions feel most like the home you would want to live in?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Modern Clean",
        description: "Simple, crisp, minimal — beautifully uncluttered",
        signals: ["MCL", "WM"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "⬜",
      },
      {
        id: "B",
        label: "Warm Natural",
        description: "Warm woods, organic textures, relaxed luxury",
        signals: ["WN", "OM"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🪵",
      },
      {
        id: "C",
        label: "Classic Elevated",
        description: "Timeless, formal, premium investment",
        signals: ["CE", "TR"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Coastal Light",
        description: "Relaxed, bright, casual coastal luxury",
        signals: ["CL", "CC"],
        gradient: "from-sky-400 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Textured",
        description: "Character, warmth, handcrafted detail",
        signals: ["MT", "MS"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Organic Spa",
        description: "Wellness, quiet luxury, calm and elevated",
        signals: ["OS", "OM"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Cottage Character",
        description: "Personality, warmth, cozy detail",
        signals: ["CTG", "MC"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Rustic / Industrial",
        description: "Bold, durable, dramatic and raw",
        signals: ["RI", "MM", "MB"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "⚙️",
      },
    ],
  },

  {
    id: "int_2",
    prompt: "Which flooring directions would you want considered throughout your new home?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Wide-Plank White Oak",
        description: "Warm, natural, timeless luxury",
        signals: ["WN", "OS", "CL"],
        gradient: "from-amber-600 to-stone-400",
        emoji: "🪵",
      },
      {
        id: "B",
        label: "Medium Warm Oak",
        description: "Warmth, family-friendly, versatile",
        signals: ["WN", "MF", "TR"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "🌳",
      },
      {
        id: "C",
        label: "Durable Wood-Look LVP",
        description: "Practical, low-maintenance, family durability",
        signals: ["MF"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "✅",
      },
      {
        id: "D",
        label: "Large-Format Porcelain Tile",
        description: "Modern, durable, easy to maintain",
        signals: ["MCL", "WM", "CC"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "⬜",
      },
      {
        id: "E",
        label: "Natural Stone-Look Tile",
        description: "Organic luxury, elevated character",
        signals: ["OS", "MT", "MS"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🪨",
      },
      {
        id: "F",
        label: "Patterned Tile in Select Areas",
        description: "Personality, design moments",
        signals: ["CTG", "MT"],
        gradient: "from-rose-600 to-amber-400",
        emoji: "🎨",
      },
      {
        id: "G",
        label: "Dark Wood / Rich Flooring",
        description: "Drama, depth, sophisticated character",
        signals: ["CE", "RI", "MM"],
        gradient: "from-stone-900 to-stone-600",
        emoji: "🖤",
      },
      {
        id: "H",
        label: "Concrete / Polished Modern",
        description: "Bold, industrial-modern statement",
        signals: ["MCL", "RI", "WM"],
        gradient: "from-zinc-700 to-zinc-500",
        emoji: "🏗️",
      },
    ],
  },

  {
    id: "int_3",
    prompt: "Which cabinet door styles are you most drawn to?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Flat Slab Cabinet Doors",
        description: "Modern, clean, minimal",
        signals: ["MCL", "WM"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "▭",
      },
      {
        id: "B",
        label: "Slim Shaker Cabinets",
        description: "Versatile, warm, transitional",
        signals: ["WN", "MF", "TR"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "📋",
      },
      {
        id: "C",
        label: "Traditional Shaker Cabinets",
        description: "Timeless, familiar, classic",
        signals: ["MF", "TR", "CE"],
        gradient: "from-zinc-500 to-zinc-300",
        emoji: "🏠",
      },
      {
        id: "D",
        label: "Inset Cabinetry",
        description: "Premium, precise, elevated craftsmanship",
        signals: ["CE", "TR"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "✦",
      },
      {
        id: "E",
        label: "Reeded or Fluted Detail",
        description: "Custom, textured, design-forward",
        signals: ["OM", "WN"],
        gradient: "from-stone-600 to-stone-400",
        emoji: "🎵",
      },
      {
        id: "F",
        label: "Arched / Furniture-Style",
        description: "Character, warmth, custom personality",
        signals: ["MS", "CTG", "MT"],
        gradient: "from-rose-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "G",
        label: "Beadboard / Cottage Detail",
        description: "Cottage charm, layered personality",
        signals: ["CTG", "MC"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Metal / Glass / Industrial",
        description: "Dramatic, bold, industrial edge",
        signals: ["RI", "MM"],
        gradient: "from-stone-800 to-zinc-600",
        emoji: "⚙️",
      },
    ],
  },

  {
    id: "int_4",
    prompt: "Which countertop styles are you most drawn to?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Clean White Quartz",
        description: "Crisp, clean, versatile",
        signals: ["MCL", "CL"],
        gradient: "from-zinc-200 to-white",
        emoji: "⬜",
      },
      {
        id: "B",
        label: "Warm Marble-Look Quartz",
        description: "Timeless, elegant, warm veining",
        signals: ["CE", "WN"],
        gradient: "from-stone-200 to-white",
        emoji: "🤍",
      },
      {
        id: "C",
        label: "Dramatic Veined Slab",
        description: "Statement, luxury, custom centerpiece",
        signals: ["WM", "CE"],
        gradient: "from-zinc-700 to-stone-400",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Honed Stone Look",
        description: "Organic, spa-inspired, calm luxury",
        signals: ["OS", "MT", "OM"],
        gradient: "from-stone-400 to-stone-200",
        emoji: "🪨",
      },
      {
        id: "E",
        label: "Concrete-Look Surface",
        description: "Industrial-modern, durable, bold",
        signals: ["RI", "MCL", "WM"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "🏗️",
      },
      {
        id: "F",
        label: "Butcher Block / Wood Accent",
        description: "Warm, casual, character accent",
        signals: ["MF", "CTG", "WN"],
        gradient: "from-amber-700 to-stone-500",
        emoji: "🪵",
      },
      {
        id: "G",
        label: "Dark Countertops",
        description: "Dramatic, bold, sophisticated depth",
        signals: ["RI", "MM"],
        gradient: "from-stone-900 to-stone-700",
        emoji: "🖤",
      },
      {
        id: "H",
        label: "Quartzite / Natural Stone Luxury",
        description: "Premium, elevated, genuine luxury",
        signals: ["CE", "WM", "OS"],
        gradient: "from-stone-400 to-stone-200",
        emoji: "💎",
      },
    ],
  },

  {
    id: "int_5",
    prompt: "Which kitchen direction feels right for your new home?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Warm Modern Kitchen",
        description: "Clean, warm, refined — elevated daily cooking",
        signals: ["WM", "WN", "MCL"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "👨‍🍳",
      },
      {
        id: "B",
        label: "Modern Farmhouse Kitchen",
        description: "Casual, family-friendly, welcoming",
        signals: ["MF", "CTG"],
        gradient: "from-slate-600 to-slate-300",
        emoji: "🌾",
      },
      {
        id: "C",
        label: "Classic Elevated Kitchen",
        description: "Formal, timeless, premium investment",
        signals: ["TR", "CE"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Coastal Light Kitchen",
        description: "Bright, relaxed, airy palette",
        signals: ["CC", "CL"],
        gradient: "from-sky-400 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Textured Kitchen",
        description: "Warm, handcrafted, layered character",
        signals: ["MS", "MT"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Organic Minimal Kitchen",
        description: "Calm, quiet luxury, clean simplicity",
        signals: ["OM", "OS"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Cottage Character Kitchen",
        description: "Charm, personality, detailed warmth",
        signals: ["MC", "CTG"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Rustic / Industrial Kitchen",
        description: "Dramatic, masculine, durable and bold",
        signals: ["MM", "RI"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🔩",
      },
    ],
  },

  {
    id: "int_6",
    prompt: "Which lighting styles feel right for your new home?",
    type: "multi",
    options: [
      {
        id: "A",
        label: "Minimal Modern Fixtures",
        description: "Clean, architectural, understated",
        signals: ["MCL", "WM"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "💡",
      },
      {
        id: "B",
        label: "Warm Woven / Natural Fixtures",
        description: "Organic, textural, relaxed luxury",
        signals: ["WN", "OM", "CL"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🏺",
      },
      {
        id: "C",
        label: "Classic Lanterns / Chandeliers",
        description: "Timeless, formal, elevated character",
        signals: ["CE", "TR"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "🕯️",
      },
      {
        id: "D",
        label: "Coastal Casual Pendants",
        description: "Relaxed, airy, casual luxury",
        signals: ["CL", "CC"],
        gradient: "from-sky-400 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Iron / Brass Lighting",
        description: "Warm, handcrafted, regional character",
        signals: ["MT", "MS"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Sculptural Statement Lighting",
        description: "Custom, design-forward, art-like",
        signals: ["WM", "CE"],
        gradient: "from-amber-600 to-stone-400",
        emoji: "✨",
      },
      {
        id: "G",
        label: "Cottage Vintage-Inspired",
        description: "Character, charm, personality",
        signals: ["CTG", "MC"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Industrial / Rustic Fixtures",
        description: "Raw, bold, dramatic edge",
        signals: ["RI", "MM"],
        gradient: "from-stone-800 to-stone-600",
        emoji: "⚙️",
      },
    ],
  },

  {
    id: "int_7",
    prompt: "Which primary bathroom would you most want to wake up to every day?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Clean Modern Spa",
        description: "Crisp, spa-like, elevated calm",
        signals: ["MCL", "WM", "OS"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "✦",
      },
      {
        id: "B",
        label: "Warm Organic Spa",
        description: "Natural materials, soft warmth, wellness",
        signals: ["OS", "WN", "OM"],
        gradient: "from-amber-600 to-stone-400",
        emoji: "🧘",
      },
      {
        id: "C",
        label: "Classic Marble Bath",
        description: "Timeless luxury, polished, enduring",
        signals: ["CE", "TR"],
        gradient: "from-stone-300 to-white",
        emoji: "💎",
      },
      {
        id: "D",
        label: "Coastal Light Bath",
        description: "Airy, relaxed, bright and casual",
        signals: ["CL", "CC"],
        gradient: "from-sky-400 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Textured Bath",
        description: "Textured, romantic, handcrafted detail",
        signals: ["MT", "MS"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Cottage Character Bath",
        description: "Cozy, charming, warm personality",
        signals: ["CTG", "MC"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "G",
        label: "Dramatic Dark Spa",
        description: "Moody, sophisticated, statement retreat",
        signals: ["RI", "MM", "WM"],
        gradient: "from-zinc-900 to-zinc-600",
        emoji: "🖤",
      },
      {
        id: "H",
        label: "Resort-Style Wet Room",
        description: "Premium, open, full spa experience",
        signals: ["OS", "WM", "CC"],
        gradient: "from-teal-700 to-cyan-300",
        emoji: "🏊",
      },
    ],
  },

  {
    id: "int_8",
    prompt: "How do you prefer your main living spaces to flow?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Fully Open Concept",
        description: "Kitchen, dining, and living as one seamless space",
        signals: ["CC", "WM", "MCL"],
        gradient: "from-sky-500 to-cyan-200",
        emoji: "↔️",
      },
      {
        id: "B",
        label: "Semi-Open with Soft Definition",
        description: "Connected but with some structure between zones",
        signals: ["MF", "TR", "WN"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🏡",
      },
      {
        id: "C",
        label: "Defined Rooms with Character",
        description: "Distinct rooms — each with its own personality",
        signals: ["TR", "CE", "MC"],
        gradient: "from-zinc-600 to-zinc-400",
        emoji: "🏛️",
      },
      {
        id: "D",
        label: "Dramatic Great Room as Centerpiece",
        description: "One grand volume space anchoring the home",
        signals: ["MB", "MM", "WM"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "🗼",
      },
    ],
  },

  {
    id: "int_9",
    prompt: "Which interior color story speaks most to you?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Warm & Earthy",
        description: "Taupes, warm whites, natural wood, amber accents",
        signals: ["WN", "OM", "MT"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🍂",
      },
      {
        id: "B",
        label: "Cool & Crisp",
        description: "True whites, light grays, black accents, minimal palette",
        signals: ["MCL", "CC"],
        gradient: "from-zinc-500 to-zinc-200",
        emoji: "❄️",
      },
      {
        id: "C",
        label: "Layered Neutral",
        description: "Greiges, soft stone, aged brass, textured neutrals",
        signals: ["CE", "OS", "WN"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🏺",
      },
      {
        id: "D",
        label: "Bright & Coastal Light",
        description: "Whites with soft blues, seafoam, sandy driftwood tones",
        signals: ["CL", "CC"],
        gradient: "from-sky-300 to-cyan-100",
        emoji: "🏖️",
      },
      {
        id: "E",
        label: "Moody & Sophisticated",
        description: "Deep greens, charcoal, aged bronze, dramatic depth",
        signals: ["RI", "MM", "CE"],
        gradient: "from-stone-800 to-zinc-600",
        emoji: "🌑",
      },
      {
        id: "F",
        label: "Warm Character & Charm",
        description: "Brick-toned reds, antique whites, heritage greens",
        signals: ["CTG", "MC"],
        gradient: "from-rose-700 to-stone-400",
        emoji: "🌸",
      },
    ],
  },

  {
    id: "int_10",
    prompt:
      "Which complete interior finish package feels most like the direction you would want us to design?",
    type: "single",
    options: [
      {
        id: "A",
        label: "Modern Clean Package",
        description: "MCL + WM — crisp, precise, minimally beautiful",
        signals: ["MCL", "WM"],
        gradient: "from-zinc-700 to-zinc-400",
        emoji: "⬜",
      },
      {
        id: "B",
        label: "Warm Natural Package",
        description: "WN + OM — organic, warm, relaxed luxury",
        signals: ["WN", "OM"],
        gradient: "from-amber-700 to-stone-400",
        emoji: "🪵",
      },
      {
        id: "C",
        label: "Classic Elevated Package",
        description: "CE + TR — timeless, formal, premium",
        signals: ["CE", "TR"],
        gradient: "from-zinc-600 to-zinc-300",
        emoji: "✦",
      },
      {
        id: "D",
        label: "Coastal Light Package",
        description: "CL + CC — airy, bright, coastal luxury",
        signals: ["CL", "CC"],
        gradient: "from-sky-500 to-cyan-200",
        emoji: "🌊",
      },
      {
        id: "E",
        label: "Mediterranean Textured Package",
        description: "MT + MS — character, warmth, handcrafted",
        signals: ["MT", "MS"],
        gradient: "from-orange-600 to-amber-400",
        emoji: "🌿",
      },
      {
        id: "F",
        label: "Organic Spa Package",
        description: "OS + OM — wellness, quiet, elevated calm",
        signals: ["OS", "OM"],
        gradient: "from-stone-500 to-stone-300",
        emoji: "🧘",
      },
      {
        id: "G",
        label: "Cottage Character Package",
        description: "CTG + MC — personality, charm, layered detail",
        signals: ["CTG", "MC"],
        gradient: "from-rose-500 to-stone-300",
        emoji: "🌸",
      },
      {
        id: "H",
        label: "Rustic / Industrial Package",
        description: "RI + MM — bold, dramatic, raw and durable",
        signals: ["RI", "MM", "MB"],
        gradient: "from-stone-800 to-stone-500",
        emoji: "⚙️",
      },
    ],
  },
];
