export type AnswerType =
  | "multi-select"
  | "single-select"
  | "multi-select-limited"
  | "text"
  | "contact";

export type Weight = "strong" | "medium" | "supportive";

export interface QuizOption {
  id: string;
  label: string;
  description: string;
  signals: string[];
  gradient: string;
  emoji: string;
}

export interface QuizQuestion {
  id: number;
  section: number;
  sectionTitle: string;
  clientPrompt: string;
  answerType: AnswerType;
  weight: Weight;
  options?: QuizOption[];
  maxSelections?: number;
  placeholder?: string;
}

// Architectural Style Codes: WM MF TR CC MS OM MC MB MM MP
// Interior Finish Codes: MCL WN CE CL MT OS CTG RI

export const SECTIONS = [
  { number: 1, title: "Exterior Style", subtitle: "Tell us about your dream home's exterior" },
  { number: 2, title: "Exterior Details", subtitle: "Refine your architectural direction" },
  { number: 3, title: "Interior Finishes", subtitle: "Discover your interior design language" },
  { number: 4, title: "Finish Details", subtitle: "Narrow down the details that matter" },
  { number: 5, title: "Home Program", subtitle: "Size, rooms, and lifestyle features" },
  { number: 6, title: "Site & Scope", subtitle: "Outdoor living, lot, and priorities" },
  { number: 7, title: "Your Goals", subtitle: "Help us understand you" },
];

export const QUESTIONS: QuizQuestion[] = [
  // ─── SECTION 1: ARCHITECTURAL STYLE ───────────────────────────────────────
  {
    id: 1,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "Which exterior homes are you most drawn to for your new home?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Warm Modern Retreat", description: "Clean massing, large glass, warm wood accents — modern but livable", signals: ["WM","OM"], gradient: "from-amber-700 to-stone-500", emoji: "🏡" },
      { id: "B", label: "Modern Farmhouse 2.0", description: "Gabled roofs, white & black palette, approachable luxury", signals: ["MF","TR"], gradient: "from-slate-700 to-slate-400", emoji: "🌾" },
      { id: "C", label: "New Traditional Estate", description: "Symmetry, timelessness, classic curb appeal, resale confidence", signals: ["TR","CE"], gradient: "from-zinc-700 to-zinc-500", emoji: "🏛️" },
      { id: "D", label: "Coastal Contemporary", description: "Light palette, pool lifestyle, natural light, casual luxury", signals: ["CC","CL"], gradient: "from-sky-600 to-cyan-300", emoji: "🌊" },
      { id: "E", label: "Modern Mediterranean", description: "Arches, texture, courtyard, romantic exterior, regional character", signals: ["MS","MT"], gradient: "from-orange-700 to-amber-500", emoji: "🌿" },
      { id: "F", label: "European Cottage Modern", description: "Character, warmth, charm, intimate luxury, layered detail", signals: ["MC","TR","CTG"], gradient: "from-stone-600 to-stone-400", emoji: "🌸" },
      { id: "G", label: "Modern Barn Residence", description: "Dramatic volume, utility, flexible living, strong masculine edge", signals: ["MB","MM"], gradient: "from-stone-800 to-neutral-600", emoji: "🏗️" },
      { id: "H", label: "Modern Prairie", description: "Horizontal massing, privacy, indoor-outdoor connection, refined calm", signals: ["MP","WM","OM"], gradient: "from-amber-900 to-stone-600", emoji: "🌅" },
    ],
  },
  {
    id: 2,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "Which overall home shape feels closest to what you would want?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Simple Rectangular Modern", description: "Clean, efficient, modern form", signals: ["WM","MP","MCL"], gradient: "from-zinc-700 to-zinc-400", emoji: "◻️" },
      { id: "B", label: "Classic Symmetrical Front", description: "Formal, timeless, resale-friendly", signals: ["TR","CE"], gradient: "from-stone-600 to-stone-400", emoji: "⚖️" },
      { id: "C", label: "Gabled Family Home", description: "Approachable, casual, traditional-modern blend", signals: ["MF","MC"], gradient: "from-slate-600 to-slate-400", emoji: "🏠" },
      { id: "D", label: "Courtyard-Oriented Home", description: "Indoor-outdoor living, privacy, resort feel", signals: ["MS","CC","OM"], gradient: "from-amber-700 to-orange-400", emoji: "🏡" },
      { id: "E", label: "L-Shape or U-Shape Plan", description: "Functional zoning, outdoor planning, privacy", signals: ["WM","CC","MP"], gradient: "from-teal-700 to-teal-400", emoji: "📐" },
      { id: "F", label: "Tall Volume Statement", description: "Drama, scale, custom design, bold presence", signals: ["MB","MM","WM"], gradient: "from-stone-800 to-stone-500", emoji: "🗼" },
      { id: "G", label: "Long Low Horizontal", description: "Calm, private, land-hugging architecture", signals: ["MP","OM","WM"], gradient: "from-amber-800 to-stone-500", emoji: "➡️" },
      { id: "H", label: "Layered Cottage Massing", description: "Character, detail, intimate scale", signals: ["MC","TR","CTG"], gradient: "from-rose-700 to-stone-400", emoji: "🌺" },
    ],
  },
  {
    id: 3,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "Which rooflines would you want considered for your new home?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Low-Slope Modern Roof", description: "Sleek, horizontal, contemporary", signals: ["WM","MP"], gradient: "from-zinc-700 to-zinc-500", emoji: "▱" },
      { id: "B", label: "Simple Gable Roof", description: "Familiar, warm, clean", signals: ["MF","MC","MB"], gradient: "from-slate-600 to-slate-400", emoji: "⛺" },
      { id: "C", label: "Multiple Gables", description: "Detailed, classic, family home feel", signals: ["TR","MC","MF"], gradient: "from-stone-600 to-stone-300", emoji: "🏘️" },
      { id: "D", label: "Hip Roof Traditional", description: "Timeless, formal, resale-friendly", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-400", emoji: "🏠" },
      { id: "E", label: "Flat Tile / Low Mediterranean", description: "Regional, warm, textured character", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🫙" },
      { id: "F", label: "Steep Cottage Roof", description: "Charm, character, intimate detail", signals: ["MC","CTG"], gradient: "from-rose-600 to-stone-400", emoji: "🏡" },
      { id: "G", label: "Dramatic Barn Roof", description: "Volume, utility, statement architecture", signals: ["MB","MM","RI"], gradient: "from-stone-800 to-stone-600", emoji: "🏚️" },
      { id: "H", label: "Mixed Modern Roofline", description: "Custom, layered, contemporary blend", signals: ["WM","OM","MP"], gradient: "from-amber-700 to-stone-500", emoji: "✦" },
    ],
  },
  {
    id: 4,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "Which exterior material combinations are you most drawn to?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Stucco + Wood + Stone", description: "Warm natural, refined modern blend", signals: ["WM","OM","MS"], gradient: "from-amber-700 to-stone-500", emoji: "🪵" },
      { id: "B", label: "White Siding + Black Windows + Metal", description: "Clean contrast, modern farmhouse feel", signals: ["MF","TR"], gradient: "from-slate-800 to-slate-400", emoji: "🖤" },
      { id: "C", label: "Brick + Painted Trim", description: "Timeless, formal, excellent resale", signals: ["TR","CE"], gradient: "from-red-800 to-rose-600", emoji: "🧱" },
      { id: "D", label: "Smooth Stucco + Arches + Iron", description: "Romantic, textured, regional character", signals: ["MS","MT"], gradient: "from-orange-700 to-amber-500", emoji: "🌿" },
      { id: "E", label: "Light Stucco + Pale Stone + Glass", description: "Light, airy, pool-oriented luxury", signals: ["CC","CL"], gradient: "from-sky-500 to-cyan-200", emoji: "💎" },
      { id: "F", label: "Stone + Timber + Dark Windows", description: "Dramatic, grounded, masculine presence", signals: ["MM","MB","RI"], gradient: "from-stone-800 to-stone-600", emoji: "🪨" },
      { id: "G", label: "Mixed Stone + Soft Brick + Trim", description: "Character, layered detail, warmth", signals: ["MC","CTG","TR"], gradient: "from-stone-600 to-rose-400", emoji: "🌸" },
      { id: "H", label: "Dark Metal + Wood + Glass", description: "Bold, custom, dramatic statement", signals: ["MB","WM","RI"], gradient: "from-zinc-800 to-stone-600", emoji: "⚡" },
    ],
  },
  {
    id: 5,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "Which exterior color palettes feel right for your new home?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Warm White + Natural Wood + Soft Stone", description: "Soft, clean, warm luxury", signals: ["WM","OM","CC"], gradient: "from-amber-200 to-stone-300", emoji: "🤍" },
      { id: "B", label: "Crisp White + Black Accents", description: "Contrast, simple, modern familiar", signals: ["MF","TR"], gradient: "from-slate-900 to-white", emoji: "◐" },
      { id: "C", label: "Soft Greige + Taupe + Bronze", description: "Understated luxury, refined warmth", signals: ["WM","MS","OM"], gradient: "from-amber-700 to-stone-300", emoji: "🏺" },
      { id: "D", label: "Charcoal + Wood + Stone", description: "Dramatic, bold, strong presence", signals: ["MB","MM","RI"], gradient: "from-zinc-800 to-stone-500", emoji: "🖤" },
      { id: "E", label: "Pale Coastal Whites + Sand Tones", description: "Relaxed, airy, outdoor-focused", signals: ["CC","CL"], gradient: "from-sky-200 to-amber-100", emoji: "🏖️" },
      { id: "F", label: "Earthy Mediterranean Tones", description: "Warm, regional, handcrafted texture", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌺" },
      { id: "G", label: "Classic Brick or Painted Brick", description: "Classic, refined, enduring appeal", signals: ["TR","CE","MC"], gradient: "from-red-700 to-rose-500", emoji: "🧱" },
      { id: "H", label: "Organic Monochrome Neutrals", description: "Calm, natural, elevated simplicity", signals: ["OM","OS","WN"], gradient: "from-stone-500 to-stone-300", emoji: "🌿" },
    ],
  },
  {
    id: 6,
    section: 1,
    sectionTitle: "Exterior Style",
    clientPrompt: "What kind of front entry experience would you want for your new home?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Tall Modern Glass Entry", description: "Custom, dramatic, modern welcome", signals: ["WM","OM"], gradient: "from-zinc-700 to-zinc-400", emoji: "🚪" },
      { id: "B", label: "Covered Farmhouse Porch", description: "Casual, family, approachable warmth", signals: ["MF"], gradient: "from-slate-600 to-slate-300", emoji: "🌾" },
      { id: "C", label: "Formal Symmetrical Entry", description: "Timeless, formal, impressive arrival", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-400", emoji: "⚖️" },
      { id: "D", label: "Arched Mediterranean Entry", description: "Romantic, textured, distinctive character", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "E", label: "Coastal Breezeway Entry", description: "Relaxed, airy, outdoor connection", signals: ["CC","CL"], gradient: "from-sky-500 to-cyan-300", emoji: "🌊" },
      { id: "F", label: "Cottage Garden Entry", description: "Warmth, character, charming approach", signals: ["MC","CTG"], gradient: "from-rose-500 to-stone-400", emoji: "🌸" },
      { id: "G", label: "Barn-Style Oversized Entry", description: "Statement, dramatic scale, bold", signals: ["MB","MM"], gradient: "from-stone-700 to-stone-500", emoji: "🚪" },
      { id: "H", label: "Private Courtyard Entry", description: "Resort-like, private, high-end experience", signals: ["MS","OM","CC"], gradient: "from-teal-700 to-amber-500", emoji: "🏡" },
    ],
  },

  // ─── SECTION 2: MORE ARCHITECTURAL ────────────────────────────────────────
  {
    id: 7,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "Which window and natural light styles are you most drawn to?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Large Modern Black Windows", description: "Modern, bright, strong visual frame", signals: ["WM","MP","MCL"], gradient: "from-zinc-800 to-zinc-500", emoji: "⬛" },
      { id: "B", label: "Gridded Farmhouse Windows", description: "Familiar, warm, traditional feel", signals: ["MF","MC","CTG"], gradient: "from-slate-600 to-slate-300", emoji: "🔲" },
      { id: "C", label: "Classic Divided-Light Windows", description: "Timeless, formal, refined detail", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-400", emoji: "🪟" },
      { id: "D", label: "Arched Windows", description: "Romantic, architectural detail, statement", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "E", label: "Floor-to-Ceiling Glass Walls", description: "Indoor-outdoor, luxury, expansive light", signals: ["WM","CC","OM"], gradient: "from-sky-600 to-cyan-300", emoji: "✨" },
      { id: "F", label: "Clerestory Windows", description: "Modern, private, design sophistication", signals: ["MP","OM"], gradient: "from-amber-700 to-stone-400", emoji: "💡" },
      { id: "G", label: "Cottage-Style Windows", description: "Character, charm, intimate scale", signals: ["MC","CTG"], gradient: "from-rose-500 to-stone-400", emoji: "🌸" },
      { id: "H", label: "Sliding / Folding Glass Doors", description: "Outdoor priority, entertaining, open living", signals: ["CC","WM","OM"], gradient: "from-teal-600 to-cyan-300", emoji: "🏡" },
    ],
  },
  {
    id: 8,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "Which garage and arrival layouts would you want considered?",
    answerType: "multi-select",
    weight: "supportive",
    options: [
      { id: "A", label: "Side-Entry Garage", description: "Upscale curb appeal, garage de-emphasized", signals: ["TR","WM"], gradient: "from-zinc-600 to-zinc-400", emoji: "🚗" },
      { id: "B", label: "Front-Load with Upgraded Doors", description: "Practical, design integrated", signals: ["MF","TR"], gradient: "from-slate-600 to-slate-400", emoji: "🏠" },
      { id: "C", label: "Detached / Carriage House", description: "Estate feel, flexibility, character", signals: ["MC","MF","MB"], gradient: "from-stone-600 to-stone-400", emoji: "🏡" },
      { id: "D", label: "Motor Court Arrival", description: "Luxury, formal, custom impression", signals: ["TR","MS","WM"], gradient: "from-amber-700 to-stone-500", emoji: "✦" },
      { id: "E", label: "Oversized Workshop Garage", description: "Utility, lifestyle function, hobbyist", signals: ["MB","MM","RI"], gradient: "from-stone-800 to-stone-600", emoji: "🔧" },
      { id: "F", label: "Hidden / Recessed Garage", description: "Design-forward, strong curb appeal", signals: ["WM","MP","OM"], gradient: "from-zinc-700 to-zinc-500", emoji: "👁️" },
      { id: "G", label: "RV / Boat / Toy Storage", description: "Function-heavy, land-oriented", signals: ["MB","MM"], gradient: "from-stone-700 to-stone-500", emoji: "🚤" },
      { id: "H", label: "Porte-Cochère / Covered Arrival", description: "Luxury, formal hospitality", signals: ["TR","MS","CE"], gradient: "from-amber-700 to-stone-400", emoji: "🏛️" },
    ],
  },
  {
    id: 9,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "Which outdoor living and pool areas would you want planned from the beginning?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Modern Covered Lanai + Pool View", description: "Indoor-outdoor, entertaining, resort feel", signals: ["WM","CC","OM"], gradient: "from-teal-600 to-cyan-300", emoji: "🏊" },
      { id: "B", label: "Farmhouse Porch + Outdoor Fireplace", description: "Casual comfort, gathering, cozy outdoor", signals: ["MF","MC"], gradient: "from-amber-700 to-stone-500", emoji: "🔥" },
      { id: "C", label: "Formal Pool Terrace", description: "Classic luxury, formal entertaining", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-300", emoji: "✦" },
      { id: "D", label: "Mediterranean Courtyard Pool", description: "Private, resort, romantic character", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "E", label: "Coastal Resort Pool", description: "Resort lifestyle, bright, social", signals: ["CC","CL"], gradient: "from-sky-500 to-cyan-200", emoji: "🌊" },
      { id: "F", label: "Organic Spa Courtyard", description: "Privacy, wellness, calm retreat", signals: ["OM","OS"], gradient: "from-stone-600 to-stone-400", emoji: "🧘" },
      { id: "G", label: "Rustic Modern Outdoor Living", description: "Drama, entertaining, grounded feel", signals: ["MM","RI"], gradient: "from-stone-800 to-stone-500", emoji: "🏕️" },
      { id: "H", label: "Large Land-Based Outdoor Zone", description: "Acreage, function, active lifestyle", signals: ["MB","MM"], gradient: "from-amber-800 to-stone-600", emoji: "🌄" },
    ],
  },
  {
    id: 10,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "When you imagine walking into your new home, which main living spaces feel most like what you want?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Warm Modern Open Living", description: "Clean but warm, elevated comfort", signals: ["WM","WN","OM"], gradient: "from-amber-700 to-stone-400", emoji: "🏡" },
      { id: "B", label: "Bright Farmhouse Great Room", description: "Casual, family-oriented, open", signals: ["MF","CTG"], gradient: "from-slate-600 to-slate-300", emoji: "🌾" },
      { id: "C", label: "Elegant Transitional Living", description: "Polished, timeless, refined", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-400", emoji: "✦" },
      { id: "D", label: "Coastal Light Open Space", description: "Relaxed, bright, casual luxury", signals: ["CC","CL"], gradient: "from-sky-500 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Textured Living", description: "Romantic, textured, warm character", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Organic Spa-Inspired Living", description: "Calm, wellness, soft modern luxury", signals: ["OM","OS"], gradient: "from-stone-500 to-stone-300", emoji: "🧘" },
      { id: "G", label: "Cottage Character Living", description: "Cozy, detailed, intimate", signals: ["MC","CTG"], gradient: "from-rose-500 to-stone-400", emoji: "🌸" },
      { id: "H", label: "Rustic Modern Volume Space", description: "Dramatic, high-volume, statement", signals: ["MM","MB","RI"], gradient: "from-stone-800 to-stone-500", emoji: "🏗️" },
    ],
  },
  {
    id: 11,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "Which kitchen directions would you want considered for your new home?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Warm Modern Kitchen", description: "Clean, warm, refined — elevated daily cooking", signals: ["WM","WN","MCL"], gradient: "from-amber-700 to-stone-400", emoji: "👨‍🍳" },
      { id: "B", label: "Modern Farmhouse Kitchen", description: "Casual, family-friendly, welcoming", signals: ["MF","CTG"], gradient: "from-slate-600 to-slate-300", emoji: "🌾" },
      { id: "C", label: "Classic Elevated Kitchen", description: "Formal, timeless, premium investment", signals: ["TR","CE"], gradient: "from-zinc-600 to-zinc-300", emoji: "✦" },
      { id: "D", label: "Coastal Light Kitchen", description: "Bright, relaxed, airy palette", signals: ["CC","CL"], gradient: "from-sky-400 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Textured Kitchen", description: "Warm, handcrafted, layered character", signals: ["MS","MT"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Organic Minimal Kitchen", description: "Calm, quiet luxury, clean simplicity", signals: ["OM","OS"], gradient: "from-stone-500 to-stone-300", emoji: "🧘" },
      { id: "G", label: "Cottage Character Kitchen", description: "Charm, personality, detailed warmth", signals: ["MC","CTG"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "H", label: "Rustic / Industrial Kitchen", description: "Dramatic, masculine, durable and bold", signals: ["MM","RI"], gradient: "from-stone-800 to-stone-500", emoji: "🔩" },
    ],
  },
  {
    id: 18,
    section: 2,
    sectionTitle: "Exterior Details",
    clientPrompt: "If you had to choose the direction that feels most exciting for your new home, which images would you want us to study most closely?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Clean Warm Modern New Build", description: "WM + OM — the highest-confidence modern direction", signals: ["WM","OM"], gradient: "from-amber-700 to-stone-400", emoji: "🏡" },
      { id: "B", label: "Refined Modern Farmhouse New Build", description: "MF + TR — family-friendly approachable luxury", signals: ["MF","TR"], gradient: "from-slate-700 to-slate-400", emoji: "🌾" },
      { id: "C", label: "Transitional Estate New Build", description: "TR + CE — resale-friendly timeless design", signals: ["TR","CE"], gradient: "from-zinc-700 to-zinc-400", emoji: "🏛️" },
      { id: "D", label: "Coastal Contemporary New Build", description: "CC + CL — outdoor lifestyle and resort feel", signals: ["CC","CL"], gradient: "from-sky-600 to-cyan-300", emoji: "🌊" },
      { id: "E", label: "Contemporary Mediterranean New Build", description: "MS + MT — romantic, distinctive, regional", signals: ["MS","MT"], gradient: "from-orange-700 to-amber-500", emoji: "🌿" },
      { id: "F", label: "Organic Modern New Build", description: "OM + OS — quiet luxury, wellness-inspired", signals: ["OM","OS"], gradient: "from-stone-600 to-stone-400", emoji: "🧘" },
      { id: "G", label: "Modern Cottage / European New Build", description: "MC + CTG — personality, warmth, character", signals: ["MC","CTG"], gradient: "from-rose-600 to-stone-400", emoji: "🌸" },
      { id: "H", label: "Modern Barn / Rustic Modern New Build", description: "MB + MM — scale, function, dramatic volume", signals: ["MB","MM","RI"], gradient: "from-stone-800 to-stone-500", emoji: "🏚️" },
    ],
  },

  // ─── SECTION 3: INTERIOR FINISHES ──────────────────────────────────────────
  {
    id: 19,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which interior finish directions feel most like the home you would want to live in?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Modern Clean", description: "Simple, crisp, minimal — beautifully uncluttered", signals: ["MCL","WM"], gradient: "from-zinc-700 to-zinc-400", emoji: "⬜" },
      { id: "B", label: "Warm Natural", description: "Warm woods, organic textures, relaxed luxury", signals: ["WN","OM"], gradient: "from-amber-700 to-stone-400", emoji: "🪵" },
      { id: "C", label: "Classic Elevated", description: "Timeless, formal, premium investment", signals: ["CE","TR"], gradient: "from-zinc-600 to-zinc-300", emoji: "✦" },
      { id: "D", label: "Coastal Light", description: "Relaxed, bright, casual coastal luxury", signals: ["CL","CC"], gradient: "from-sky-400 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Textured", description: "Character, warmth, handcrafted detail", signals: ["MT","MS"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Organic Spa", description: "Wellness, quiet luxury, calm and elevated", signals: ["OS","OM"], gradient: "from-stone-500 to-stone-300", emoji: "🧘" },
      { id: "G", label: "Cottage Character", description: "Personality, warmth, cozy detail", signals: ["CTG","MC"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "H", label: "Rustic / Industrial", description: "Bold, durable, dramatic and raw", signals: ["RI","MM","MB"], gradient: "from-stone-800 to-stone-500", emoji: "⚙️" },
    ],
  },
  {
    id: 20,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which flooring directions would you want considered throughout your new home?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Wide-Plank White Oak", description: "Warm, natural, timeless luxury", signals: ["WN","OS","CL"], gradient: "from-amber-600 to-stone-400", emoji: "🪵" },
      { id: "B", label: "Medium Warm Oak", description: "Warmth, family-friendly, versatile", signals: ["WN","MF","TR"], gradient: "from-amber-700 to-stone-500", emoji: "🌳" },
      { id: "C", label: "Durable Wood-Look LVP", description: "Practical, low-maintenance, family durability", signals: ["MF","practical"], gradient: "from-stone-600 to-stone-400", emoji: "✅" },
      { id: "D", label: "Large-Format Porcelain Tile", description: "Modern, durable, easy to maintain", signals: ["MCL","WM","CC"], gradient: "from-zinc-600 to-zinc-300", emoji: "⬜" },
      { id: "E", label: "Natural Stone-Look Tile", description: "Organic luxury, elevated character", signals: ["OS","MT","MS"], gradient: "from-stone-500 to-stone-300", emoji: "🪨" },
      { id: "F", label: "Patterned Tile in Select Areas", description: "Personality, design moments", signals: ["CTG","MT"], gradient: "from-rose-600 to-amber-400", emoji: "🎨" },
      { id: "G", label: "Dark Wood / Rich Flooring", description: "Drama, depth, sophisticated character", signals: ["CE","RI","MM"], gradient: "from-stone-900 to-stone-600", emoji: "🖤" },
      { id: "H", label: "Concrete / Polished Modern", description: "Bold, industrial-modern statement", signals: ["MCL","RI","WM"], gradient: "from-zinc-700 to-zinc-500", emoji: "🏗️" },
    ],
  },
  {
    id: 21,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which cabinet door styles are you most drawn to?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Flat Slab Cabinet Doors", description: "Modern, clean, minimal", signals: ["MCL","WM"], gradient: "from-zinc-700 to-zinc-400", emoji: "▭" },
      { id: "B", label: "Slim Shaker Cabinets", description: "Versatile, warm, transitional", signals: ["WN","MF","TR"], gradient: "from-stone-500 to-stone-300", emoji: "📋" },
      { id: "C", label: "Traditional Shaker Cabinets", description: "Timeless, familiar, classic", signals: ["MF","TR","CE"], gradient: "from-zinc-500 to-zinc-300", emoji: "🏠" },
      { id: "D", label: "Inset Cabinetry", description: "Premium, precise, elevated craftsmanship", signals: ["CE","TR"], gradient: "from-zinc-600 to-zinc-400", emoji: "✦" },
      { id: "E", label: "Reeded or Fluted Detail", description: "Custom, textured, design-forward", signals: ["OM","WN"], gradient: "from-stone-600 to-stone-400", emoji: "🎵" },
      { id: "F", label: "Arched / Furniture-Style", description: "Character, warmth, custom personality", signals: ["MS","CTG","MT"], gradient: "from-rose-600 to-amber-400", emoji: "🌿" },
      { id: "G", label: "Beadboard / Cottage Detail", description: "Cottage charm, layered personality", signals: ["CTG","MC"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "H", label: "Metal / Glass / Industrial", description: "Dramatic, bold, industrial edge", signals: ["RI","MM"], gradient: "from-stone-800 to-zinc-600", emoji: "⚙️" },
    ],
  },
  {
    id: 23,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which countertop styles are you most drawn to?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Clean White Quartz", description: "Crisp, clean, versatile", signals: ["MCL","CL"], gradient: "from-zinc-200 to-white", emoji: "⬜" },
      { id: "B", label: "Warm Marble-Look Quartz", description: "Timeless, elegant, warm veining", signals: ["CE","WN"], gradient: "from-stone-200 to-white", emoji: "🤍" },
      { id: "C", label: "Dramatic Veined Slab", description: "Statement, luxury, custom centerpiece", signals: ["WM","CE"], gradient: "from-zinc-700 to-stone-400", emoji: "✦" },
      { id: "D", label: "Honed Stone Look", description: "Organic, spa-inspired, calm luxury", signals: ["OS","MT","OM"], gradient: "from-stone-400 to-stone-200", emoji: "🪨" },
      { id: "E", label: "Concrete-Look Surface", description: "Industrial-modern, durable, bold", signals: ["RI","MCL","WM"], gradient: "from-zinc-600 to-zinc-400", emoji: "🏗️" },
      { id: "F", label: "Butcher Block / Wood Accent", description: "Warm, casual, character accent", signals: ["MF","CTG","WN"], gradient: "from-amber-700 to-stone-500", emoji: "🪵" },
      { id: "G", label: "Dark Countertops", description: "Dramatic, bold, sophisticated depth", signals: ["RI","MM"], gradient: "from-stone-900 to-stone-700", emoji: "🖤" },
      { id: "H", label: "Quartzite / Natural Stone Luxury", description: "Premium, elevated, genuine luxury", signals: ["CE","WM","OS"], gradient: "from-stone-400 to-stone-200", emoji: "💎" },
    ],
  },
  {
    id: 29,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which lighting styles feel right for your new home?",
    answerType: "multi-select",
    weight: "medium",
    options: [
      { id: "A", label: "Minimal Modern Fixtures", description: "Clean, architectural, understated", signals: ["MCL","WM"], gradient: "from-zinc-700 to-zinc-400", emoji: "💡" },
      { id: "B", label: "Warm Woven / Natural Fixtures", description: "Organic, textural, relaxed luxury", signals: ["WN","OM","CL"], gradient: "from-amber-700 to-stone-400", emoji: "🏺" },
      { id: "C", label: "Classic Lanterns / Chandeliers", description: "Timeless, formal, elevated character", signals: ["CE","TR"], gradient: "from-zinc-600 to-zinc-300", emoji: "🕯️" },
      { id: "D", label: "Coastal Casual Pendants", description: "Relaxed, airy, casual luxury", signals: ["CL","CC"], gradient: "from-sky-400 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Iron / Brass Lighting", description: "Warm, handcrafted, regional character", signals: ["MT","MS"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Sculptural Statement Lighting", description: "Custom, design-forward, art-like", signals: ["WM","CE"], gradient: "from-amber-600 to-stone-400", emoji: "✨" },
      { id: "G", label: "Cottage Vintage-Inspired", description: "Character, charm, personality", signals: ["CTG","MC"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "H", label: "Industrial / Rustic Fixtures", description: "Raw, bold, dramatic edge", signals: ["RI","MM"], gradient: "from-stone-800 to-stone-600", emoji: "⚙️" },
    ],
  },
  {
    id: 32,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which primary bathroom would you most want to wake up to every day?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Clean Modern Spa", description: "Crisp, spa-like, elevated calm", signals: ["MCL","WM","OS"], gradient: "from-zinc-600 to-zinc-300", emoji: "✦" },
      { id: "B", label: "Warm Organic Spa", description: "Natural materials, soft warmth, wellness", signals: ["OS","WN","OM"], gradient: "from-amber-600 to-stone-400", emoji: "🧘" },
      { id: "C", label: "Classic Marble Bath", description: "Timeless luxury, polished, enduring", signals: ["CE","TR"], gradient: "from-stone-300 to-white", emoji: "💎" },
      { id: "D", label: "Coastal Light Bath", description: "Airy, relaxed, bright and casual", signals: ["CL","CC"], gradient: "from-sky-400 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Textured Bath", description: "Textured, romantic, handcrafted detail", signals: ["MT","MS"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Cottage Character Bath", description: "Cozy, charming, warm personality", signals: ["CTG","MC"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "G", label: "Dramatic Dark Spa", description: "Moody, sophisticated, statement retreat", signals: ["RI","MM","WM"], gradient: "from-zinc-900 to-zinc-600", emoji: "🖤" },
      { id: "H", label: "Resort-Style Wet Room", description: "Premium, open, full spa experience", signals: ["OS","WM","CC"], gradient: "from-teal-700 to-cyan-300", emoji: "🏊" },
    ],
  },
  {
    id: 36,
    section: 3,
    sectionTitle: "Interior Finishes",
    clientPrompt: "Which complete finish package feels most like the direction you would want us to study for your new home?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Modern Clean Package", description: "MCL + WM — crisp, precise, minimally beautiful", signals: ["MCL","WM"], gradient: "from-zinc-700 to-zinc-400", emoji: "⬜" },
      { id: "B", label: "Warm Natural Package", description: "WN + OM — organic, warm, relaxed luxury", signals: ["WN","OM"], gradient: "from-amber-700 to-stone-400", emoji: "🪵" },
      { id: "C", label: "Classic Elevated Package", description: "CE + TR — timeless, formal, premium", signals: ["CE","TR"], gradient: "from-zinc-600 to-zinc-300", emoji: "✦" },
      { id: "D", label: "Coastal Light Package", description: "CL + CC — airy, bright, coastal luxury", signals: ["CL","CC"], gradient: "from-sky-500 to-cyan-200", emoji: "🌊" },
      { id: "E", label: "Mediterranean Textured Package", description: "MT + MS — character, warmth, handcrafted", signals: ["MT","MS"], gradient: "from-orange-600 to-amber-400", emoji: "🌿" },
      { id: "F", label: "Organic Spa Package", description: "OS + OM — wellness, quiet, elevated calm", signals: ["OS","OM"], gradient: "from-stone-500 to-stone-300", emoji: "🧘" },
      { id: "G", label: "Cottage Character Package", description: "CTG + MC — personality, charm, layered detail", signals: ["CTG","MC"], gradient: "from-rose-500 to-stone-300", emoji: "🌸" },
      { id: "H", label: "Rustic / Industrial Package", description: "RI + MM — bold, dramatic, raw and durable", signals: ["RI","MM","MB"], gradient: "from-stone-800 to-stone-500", emoji: "⚙️" },
    ],
  },

  // ─── SECTION 4: SCOPE ──────────────────────────────────────────────────────
  {
    id: 37,
    section: 4,
    sectionTitle: "Home Program",
    clientPrompt: "What approximate home size would you like considered for your new build?",
    answerType: "single-select",
    weight: "supportive",
    options: [
      { id: "A", label: "Under 2,000 sq. ft.", description: "Efficient, focused, right-sized", signals: ["small"], gradient: "from-zinc-500 to-zinc-300", emoji: "🏠" },
      { id: "B", label: "2,000–2,499 sq. ft.", description: "Comfortable family home", signals: ["small-med"], gradient: "from-zinc-600 to-zinc-400", emoji: "🏠" },
      { id: "C", label: "2,500–2,999 sq. ft.", description: "Spacious with room to live", signals: ["medium"], gradient: "from-stone-600 to-stone-400", emoji: "🏡" },
      { id: "D", label: "3,000–3,499 sq. ft.", description: "Full lifestyle home", signals: ["med-large"], gradient: "from-amber-700 to-stone-500", emoji: "🏡" },
      { id: "E", label: "3,500–3,999 sq. ft.", description: "Generous, well-appointed", signals: ["large"], gradient: "from-amber-800 to-stone-600", emoji: "🏘️" },
      { id: "F", label: "4,000–4,999 sq. ft.", description: "Luxury lifestyle footprint", signals: ["xlarge"], gradient: "from-stone-700 to-stone-500", emoji: "🏰" },
      { id: "G", label: "5,000+ sq. ft.", description: "Estate-level custom build", signals: ["estate"], gradient: "from-zinc-800 to-zinc-600", emoji: "🏛️" },
      { id: "H", label: "I'm not sure yet", description: "We'll help you figure it out", signals: ["undecided"], gradient: "from-zinc-500 to-zinc-300", emoji: "❓" },
    ],
  },
  {
    id: 38,
    section: 4,
    sectionTitle: "Home Program",
    clientPrompt: "How many stories would you prefer for your new home?",
    answerType: "single-select",
    weight: "supportive",
    options: [
      { id: "A", label: "Single-story", description: "Everything on one level — aging-friendly", signals: ["single-story"], gradient: "from-stone-500 to-stone-300", emoji: "▱" },
      { id: "B", label: "Two-story", description: "Maximizes lot use, volume upstairs", signals: ["two-story"], gradient: "from-stone-600 to-stone-400", emoji: "🏠" },
      { id: "C", label: "Main living down, guest/kids up", description: "Privacy-zoned floor plan", signals: ["split-purpose"], gradient: "from-amber-700 to-stone-500", emoji: "⬆️" },
      { id: "D", label: "Main living + primary suite downstairs", description: "Owner suite on main, flexibility up", signals: ["primary-down"], gradient: "from-amber-800 to-stone-600", emoji: "🏡" },
      { id: "E", label: "Open to either", description: "Let the design lead", signals: ["flexible"], gradient: "from-zinc-500 to-zinc-300", emoji: "↕️" },
      { id: "F", label: "Not sure yet", description: "We'll explore options together", signals: ["undecided"], gradient: "from-zinc-400 to-zinc-200", emoji: "❓" },
    ],
  },
  {
    id: 39,
    section: 4,
    sectionTitle: "Home Program",
    clientPrompt: "How many bedrooms would you like planned into the home?",
    answerType: "single-select",
    weight: "supportive",
    options: [
      { id: "A", label: "2 bedrooms", description: "", signals: ["2br"], gradient: "from-zinc-500 to-zinc-300", emoji: "🛏️" },
      { id: "B", label: "3 bedrooms", description: "", signals: ["3br"], gradient: "from-stone-500 to-stone-300", emoji: "🛏️" },
      { id: "C", label: "4 bedrooms", description: "", signals: ["4br"], gradient: "from-amber-600 to-stone-400", emoji: "🛏️" },
      { id: "D", label: "5 bedrooms", description: "", signals: ["5br"], gradient: "from-amber-700 to-stone-500", emoji: "🛏️" },
      { id: "E", label: "6+ bedrooms", description: "Estate-level program", signals: ["6br"], gradient: "from-stone-700 to-stone-500", emoji: "🛏️" },
      { id: "F", label: "Not sure yet", description: "", signals: ["undecided"], gradient: "from-zinc-400 to-zinc-200", emoji: "❓" },
    ],
  },
  {
    id: 57,
    section: 4,
    sectionTitle: "Home Program",
    clientPrompt: "Would you like a pool planned into the design from the beginning?",
    answerType: "single-select",
    weight: "strong",
    options: [
      { id: "A", label: "Yes, definitely", description: "Pool is central to our lifestyle", signals: ["pool-yes","outdoor-priority-high"], gradient: "from-cyan-600 to-sky-300", emoji: "🏊" },
      { id: "B", label: "Probably", description: "Very likely, want it designed in", signals: ["pool-likely","outdoor-priority-high"], gradient: "from-teal-600 to-cyan-300", emoji: "🌊" },
      { id: "C", label: "Maybe", description: "Want to keep the option open", signals: ["pool-maybe","outdoor-priority-med"], gradient: "from-teal-500 to-cyan-200", emoji: "💭" },
      { id: "D", label: "Plan for future pool", description: "Not now, but design it in", signals: ["pool-future","outdoor-priority-med"], gradient: "from-stone-500 to-stone-300", emoji: "📋" },
      { id: "E", label: "No", description: "Not a priority for us", signals: ["pool-no"], gradient: "from-zinc-500 to-zinc-300", emoji: "✗" },
      { id: "F", label: "Not sure yet", description: "", signals: ["undecided"], gradient: "from-zinc-400 to-zinc-200", emoji: "❓" },
    ],
  },
  {
    id: 59,
    section: 4,
    sectionTitle: "Home Program",
    clientPrompt: "Which outdoor living features should be considered for your new home?",
    answerType: "multi-select",
    weight: "strong",
    options: [
      { id: "A", label: "Covered Lanai", description: "Protected outdoor living year-round", signals: ["outdoor-lanai"], gradient: "from-teal-600 to-cyan-300", emoji: "🏡" },
      { id: "B", label: "Outdoor Kitchen", description: "Full outdoor cooking and entertaining", signals: ["outdoor-kitchen"], gradient: "from-orange-600 to-amber-400", emoji: "👨‍🍳" },
      { id: "C", label: "Outdoor Dining", description: "Dedicated al fresco dining space", signals: ["outdoor-dining"], gradient: "from-amber-600 to-stone-400", emoji: "🍽️" },
      { id: "D", label: "Outdoor Fireplace / Firepit", description: "Year-round gathering and warmth", signals: ["outdoor-fire"], gradient: "from-orange-700 to-red-500", emoji: "🔥" },
      { id: "E", label: "Pool Lounge Area", description: "Relaxed poolside living", signals: ["pool-lounge"], gradient: "from-cyan-600 to-sky-300", emoji: "🌞" },
      { id: "F", label: "Large Sliding / Folding Doors", description: "Seamless indoor-outdoor connection", signals: ["glass-walls"], gradient: "from-sky-600 to-cyan-300", emoji: "↔️" },
      { id: "G", label: "Outdoor TV / Entertainment Area", description: "Outdoor entertainment setup", signals: ["outdoor-tv"], gradient: "from-zinc-700 to-zinc-400", emoji: "📺" },
      { id: "H", label: "Cabana / Pavilion", description: "Freestanding outdoor structure", signals: ["cabana"], gradient: "from-stone-600 to-stone-400", emoji: "⛱️" },
    ],
  },

  // ─── SECTION 5: SITE & SCOPE ───────────────────────────────────────────────
  {
    id: 60,
    section: 5,
    sectionTitle: "Site & Scope",
    clientPrompt: "Do you already have land for your new home?",
    answerType: "single-select",
    weight: "supportive",
    options: [
      { id: "A", label: "Yes, I own a lot", description: "Ready to plan on your land", signals: ["lot-owned"], gradient: "from-green-600 to-emerald-400", emoji: "✅" },
      { id: "B", label: "Yes, I'm under contract", description: "Deal is in progress", signals: ["lot-contract"], gradient: "from-teal-600 to-green-400", emoji: "📋" },
      { id: "C", label: "I have a specific lot in mind", description: "Almost there", signals: ["lot-prospect"], gradient: "from-amber-600 to-stone-400", emoji: "📍" },
      { id: "D", label: "I am actively looking", description: "Searching now", signals: ["lot-searching"], gradient: "from-amber-700 to-stone-500", emoji: "🔍" },
      { id: "E", label: "I need help understanding what to look for", description: "Need lot guidance", signals: ["lot-guidance"], gradient: "from-stone-600 to-stone-400", emoji: "🗺️" },
      { id: "F", label: "I haven't started looking yet", description: "Very early stage", signals: ["lot-none"], gradient: "from-zinc-500 to-zinc-300", emoji: "🌱" },
    ],
  },
  {
    id: 62,
    section: 5,
    sectionTitle: "Site & Scope",
    clientPrompt: "What site or property features matter most to you? (Select up to 5)",
    answerType: "multi-select-limited",
    weight: "supportive",
    maxSelections: 5,
    options: [
      { id: "A", label: "Privacy", description: "Screened from neighbors and road", signals: ["privacy-high"], gradient: "from-stone-700 to-stone-500", emoji: "🌿" },
      { id: "B", label: "Views", description: "Sight lines that matter to you", signals: ["views"], gradient: "from-sky-600 to-cyan-300", emoji: "👁️" },
      { id: "C", label: "Trees / Natural Setting", description: "Natural canopy and landscape", signals: ["trees"], gradient: "from-green-700 to-emerald-400", emoji: "🌳" },
      { id: "D", label: "Outdoor Living Space", description: "Large backyard for pool and living", signals: ["outdoor-space"], gradient: "from-teal-600 to-cyan-300", emoji: "🏡" },
      { id: "E", label: "Pool Placement", description: "Ideal pool location on the lot", signals: ["pool-placement"], gradient: "from-cyan-600 to-sky-300", emoji: "🏊" },
      { id: "F", label: "Front Curb Appeal", description: "Impressive street presence", signals: ["curb-appeal"], gradient: "from-amber-600 to-stone-400", emoji: "🏠" },
      { id: "G", label: "Natural Light Orientation", description: "Sunrise, sunset, and daylight direction", signals: ["light-orientation"], gradient: "from-yellow-500 to-amber-300", emoji: "☀️" },
      { id: "H", label: "Quiet Setting", description: "Peaceful, low-traffic environment", signals: ["quiet"], gradient: "from-stone-500 to-stone-300", emoji: "🤫" },
    ],
  },
  {
    id: 69,
    section: 5,
    sectionTitle: "Site & Scope",
    clientPrompt: "Which areas would you want to prioritize most for your new home? (Select up to 5)",
    answerType: "multi-select-limited",
    weight: "medium",
    maxSelections: 5,
    options: [
      { id: "A", label: "Exterior Curb Appeal", description: "First impressions that wow", signals: ["priority-curb"], gradient: "from-amber-600 to-stone-400", emoji: "🏠" },
      { id: "B", label: "Higher-End Interior Finishes", description: "Premium materials throughout", signals: ["priority-finishes"], gradient: "from-zinc-600 to-zinc-400", emoji: "✦" },
      { id: "C", label: "Kitchen", description: "Heart of the home", signals: ["priority-kitchen"], gradient: "from-orange-600 to-amber-400", emoji: "👨‍🍳" },
      { id: "D", label: "Primary Suite", description: "Your personal retreat", signals: ["priority-suite"], gradient: "from-rose-600 to-stone-400", emoji: "🛏️" },
      { id: "E", label: "Outdoor Living / Pool", description: "Outdoor lifestyle investment", signals: ["priority-outdoor"], gradient: "from-teal-600 to-cyan-300", emoji: "🌊" },
      { id: "F", label: "Natural Light", description: "Bright, well-lit spaces", signals: ["priority-light"], gradient: "from-yellow-500 to-amber-300", emoji: "☀️" },
      { id: "G", label: "Indoor-Outdoor Connection", description: "Seamless flow inside and out", signals: ["priority-flow"], gradient: "from-sky-600 to-cyan-300", emoji: "↔️" },
      { id: "H", label: "Long-Term Resale Value", description: "Decisions that protect investment", signals: ["priority-resale"], gradient: "from-green-600 to-emerald-400", emoji: "📈" },
    ],
  },

  // ─── SECTION 6: GOALS ────────────────────────────────────────────────────
  {
    id: 70,
    section: 6,
    sectionTitle: "Your Goals",
    clientPrompt: "When would you ideally like to begin moving forward with your new home planning?",
    answerType: "single-select",
    weight: "supportive",
    options: [
      { id: "A", label: "Immediately", description: "Ready to move now", signals: ["timeline-now"], gradient: "from-green-600 to-emerald-400", emoji: "🚀" },
      { id: "B", label: "Within 1–3 months", description: "Getting serious quickly", signals: ["timeline-1-3mo"], gradient: "from-teal-600 to-green-400", emoji: "📅" },
      { id: "C", label: "Within 3–6 months", description: "Actively planning", signals: ["timeline-3-6mo"], gradient: "from-amber-600 to-stone-400", emoji: "🗓️" },
      { id: "D", label: "Within 6–12 months", description: "Planning ahead", signals: ["timeline-6-12mo"], gradient: "from-amber-700 to-stone-500", emoji: "📆" },
      { id: "E", label: "More than 12 months", description: "Long-term planning", signals: ["timeline-12mo+"], gradient: "from-stone-600 to-stone-400", emoji: "🌱" },
      { id: "F", label: "Still exploring", description: "Gathering information", signals: ["timeline-exploring"], gradient: "from-zinc-500 to-zinc-300", emoji: "💭" },
    ],
  },
  {
    id: 73,
    section: 6,
    sectionTitle: "Your Goals",
    clientPrompt: "What is the most important outcome you want from building your new home? (Select up to 3)",
    answerType: "multi-select-limited",
    weight: "supportive",
    maxSelections: 3,
    options: [
      { id: "A", label: "A beautiful home that feels custom", description: "Design-driven, unique, personal", signals: ["goal-beautiful"], gradient: "from-amber-700 to-stone-400", emoji: "✨" },
      { id: "B", label: "A home that fits our daily life", description: "Practical, functional, livable", signals: ["goal-functional"], gradient: "from-teal-600 to-cyan-300", emoji: "🏡" },
      { id: "C", label: "A home designed for entertaining", description: "Hosting-first design priorities", signals: ["goal-entertain"], gradient: "from-orange-600 to-amber-400", emoji: "🥂" },
      { id: "D", label: "A peaceful private retreat", description: "Privacy, calm, escape", signals: ["goal-retreat"], gradient: "from-stone-600 to-stone-400", emoji: "🧘" },
      { id: "E", label: "A home with strong resale value", description: "Investment-conscious decisions", signals: ["goal-resale"], gradient: "from-green-600 to-emerald-400", emoji: "📈" },
      { id: "F", label: "A home that feels luxurious", description: "Premium, elevated, impressive", signals: ["goal-luxury"], gradient: "from-amber-800 to-stone-500", emoji: "💎" },
      { id: "G", label: "A home for family life", description: "Kid-friendly, multi-generational", signals: ["goal-family"], gradient: "from-rose-600 to-stone-400", emoji: "👨‍👩‍👧‍👦" },
      { id: "H", label: "A home that feels simple and easy", description: "Low-maintenance, efficient, effortless", signals: ["goal-simple"], gradient: "from-zinc-500 to-zinc-300", emoji: "✅" },
    ],
  },
  {
    id: 75,
    section: 6,
    sectionTitle: "Your Goals",
    clientPrompt: "In your own words, describe how you want your new home to feel when you walk in.",
    answerType: "text",
    weight: "strong",
    placeholder: 'e.g. "Warm, open, and peaceful" or "Clean and modern, but not cold"',
  },

  // ─── SECTION 7: CONTACT ────────────────────────────────────────────────────
  {
    id: 76,
    section: 7,
    sectionTitle: "Your Information",
    clientPrompt: "Where should we send your personalized new home design summary?",
    answerType: "contact",
    weight: "supportive",
  },
];

export const QUESTIONS_BY_SECTION = SECTIONS.map((section) => ({
  ...section,
  questions: QUESTIONS.filter((q) => q.section === section.number),
}));
